apiVersion: v1
kind: Secret
metadata:
  name: donee-s3-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: donee-s3-charts
  type: helm
  url: https://donee-s3.s3.us-east-1.amazonaws.com/charts
  enableOCI: "false"
