apiVersion: v1
kind: Secret
metadata:
  name: donee-s3-charts
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: donee-s3-charts
  type: helm
  url: s3://donee-s3/charts
  enableOCI: "false"
