{{- if and .Values.mysql.enabled (not .Values.mysql.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "Todo_app.fullname" . }}-mysql-secret
  labels:
    {{- include "Todo_app.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  mysql-user: {{ .Values.mysql.auth.user | b64enc | quote }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  mysql-database: {{ .Values.mysql.auth.database | b64enc | quote }}
{{- end }}
