{{- if and (not .Values.unsplash.existingSecret) .Values.unsplash.accessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "Todo_app.fullname" . }}-unsplash
  labels:
    {{- include "Todo_app.labels" . | nindent 4 }}
type: Opaque
data:
  unsplash-access-key: {{ .Values.unsplash.accessKey | b64enc | quote }}
{{- end }}
